//! # gamma — A DLL‑safe, data‑driven event system
//!
//! Gamma is a type‑safe event dispatcher purpose‑built for **plugin
//! architectures** where the host and dynamically‑loaded DLLs may be compiled
//! with different compiler versions or optimisation levels.
//!
//! ## Key design
//!
//! | Concern | Solution |
//! |---|---|
//! | Stable type identity | [`Event::stable_type_id()`] returns a deterministic FNV‑1a hash of the type name, size, and alignment, generated by [`#[pulsar_event]`]. |
//! | Layout compatibility | `#[pulsar_event]` **automatically applies** `#[repr(C)]` — no manual attribute needed. |
//! | Allocator sharing | Host and plugins must link the same global allocator (e.g., `mimalloc`) so that `Box`/`Vec` created in one unit can be freed in the other. |
//! | Type versioning | Include a manual `VERSION` constant in [`Event`] and mix it into the hash if you need to evolve event structs at runtime. |
//!
//! ## Quick start
//!
//! ```rust
//! use gamma::prelude::*;
//!
//! // 1. Define an event — no manual #[repr(C)] needed
//! #[pulsar_event]
//! struct PlayerJumped {
//!     height: f32,
//!     timestamp: u64,
//! }
//!
//! // 2. Create a bus and subscribe
//! let mut bus = EventBus::new();
//!
//! bus.subscribe(|e: &PlayerJumped| {
//!     println!("Jumped {} at {}", e.height, e.timestamp);
//! });
//!
//! // 3. Publish
//! bus.publish(PlayerJumped {
//!     height: 5.0,
//!     timestamp: 12345,
//! });
//! ```
//!
//! For host‑plugin setups, repeat steps 1 and 3 in the plugin DLL and
//! step 2 in the host — the stable type ID bridges the boundary.

pub use gamma_core::*;
pub use gamma_derive::{Event, pulsar_event};

/// Convenience re-exports for the most common types.
///
/// ```rust
/// use gamma::prelude::*;
/// ```
pub mod prelude {
    pub use crate::{Event, EventBus, pulsar_event};
}
